trans_dict = {
    '实验室面积为1000m2，国际商标™和公司℠版权®。': 'The laboratory has an area of 1000m2, with international trademark™, company service mark℠, and registered copyright®. ',
    '我是第二句话。': 'I am the second sentence.',
    '我是居中': 'I am in the middle',
    '图书《计算机科学技术》是清华大学出版社发行？': "Is the book 'Computer Science and Technology' published by Tsinghua University Press? ",
    '我是第二行的第二句话。': 'I am the second sentence of the second line.',
    '大学教授 刘强、徐萌': 'University professors Liu Qiang, Xu Meng 加一个',
    '我，是一句话。': 'Me, a sentence.',
    '我,是第二句？': 'Me, the second sentence?',
    '请拆1句。': 'Please open one sentence.',
    '1立方 m³水的重量为1吨': 'Weight of 1 cubic m 3 of water is 1 ton',
    '数学公式为 ': 'The mathematical formula is', '，和': ', and',
    '的推倒过程。': 'The push-down process.',
    '此图标需要双击后，再单击按钮后生效。': 'This icon needs to be double-clicked, and then the button clicked to take effect. ',
    '列合并': 'Column Pooling',
    '行合并': 'Row pooling',
    '用户点击文档内连接，在点击文档外连接。': 'Users click on links within the document, then on links outside the document. ',
    '书名，2006年出版，作者：谭东强': 'Book title, published in 2006, author: Tan Dongqiang',
    '中国著名高等学府': 'Famous Institutions of Higher Learning in China',
    '水的质量': 'Quality of water',
    '大学教授刘强': 'University Professor Liu Qiang',
    '大学教授徐萌': 'Meng Xu, University Professor',
    '重量单位': 'Weight Units',
    '第一个批注': 'First Comment',
    '第二段批注': 'Comments to the second paragraph',
    '答复你的批注': 'Reply to your comments',
    '答复第二句': 'Response Second Sentence',
    '我是批注': 'I am a comment',
    '我是页眉，有颜色的页眉第三页': 'I am the header, the colored header on the third page',
    '第二页页眉': 'Header of page 2',
    '首页页眉': 'Header of front page',
    '第三页脚': 'Footer 3',
    '第二页脚': 'Footer 2',
    '第一页页脚': 'Footer on first page'
}
